name: flutter_application_1
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  graphql_flutter: ^5.0.0
  flutter_dotenv: ^5.0.2
  image_picker: ^0.8.4+4  # Moved inside the dependencies section

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/PeerSignet_Color_RGB.png
    - assets/pamela.png
    - assets/profile_picture.png
    ## pngs müssen noch in asset ordner gepackt werden
    - assets/john_doe.png
    - assets/jane_smith.png
    - assets/alice_brown.png
    - assets/flutter_group.png
    - assets/music_group.png
    - assets/travel_group.png
    - assets/headphones.png
    - assets/smart_watch.png
    - assets/speaker.png
    - assets/shoes.png
    - assets/smartphone.png
    - assets/laptop.png
